spring:
  application:
    name: microservice-order
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/order_db"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka